/** Definitions shown as hover tooltips on fact labels and table headers.  Keep them in one place. */
export const HELP: Record<string, string> = {
  'kind': 'prompt: the task was free text; nothing verifies it unless the run was judged. harbor: a Harbor task folder; the task\'s own tests/test.sh grades the result.',
  'reward': 'Exactly what the task\'s verifier wrote to reward.txt, shown as written and never turned into pass/fail: its meaning is up to each task. Many Harbor tasks write 1 = all tests passed, 0 = not; AlgoTune writes a speedup with a floor of 1.0, even for an invalid solution; an LLM judge writes the fraction of rubric criteria met. Read it next to the tests and the verifier exit.',
  'tests': 'passed / total test cases from the verifier\'s pytest output (verifier/stdout.log: the -v lines, or the -rA short summary). How they turn into the reward is up to the task. Only the task\'s own test files count; tests the agent wrote itself are shown as +N own. Empty when the verifier did not print per-test lines.',
  'verifier rc': 'Exit status of the verifier process itself (tests/test.sh, or the judge step), separate from the reward. 0 = it ran to completion. 124 or 142 = it hit its timeout. Anything else = the verifier broke. Many verifiers exit 1 when tests fail and still write a reward (AlgoTune does); no reward with rc != 0 usually means the verifier itself broke.',
  'exit code': 'The harness\'s own exit status inside the sandbox (rc in run.json). 124 or 142 = the agent hit its time budget. Says nothing about whether the task was solved; the reward does.',
  'status': 'rc = the harness\'s exit status inside the sandbox. unfinished = run.json has no result half yet (still running, or the runner died). proxy err = model calls the proxy could not complete upstream.',
  'wall time': 'Seconds for the agent phase only: from starting the run command to its exit. The verifier is not included.',
  's': 'Seconds for the agent phase only, verifier not included.',
  'model calls': 'Requests the harness made to the model, as recorded by the proxy on the wire (one line each in calls.jsonl).',
  'calls': 'Model requests recorded by the proxy (lines in calls.jsonl).',
  'tokens in': 'Input tokens summed over all calls, from the model\'s usage report. Each turn resends the whole conversation, so this grows quadratically with the number of turns.',
  'tokens out': 'Output tokens summed over all calls, from the model\'s usage report.',
  'tokens in / out': 'Input and output tokens summed over all recorded calls, from the model\'s usage report. Input counts the whole conversation resent on every turn.',
  'model time': 'Sum of the per-call latency the proxy measured (request in to response out). The rest of wall time is the harness running commands.',
  'proxy errors': 'Calls the proxy could not complete upstream (Bedrock error or timeout). The harness saw an error response for these.',
  'model requested': 'The model name the harness sent on the wire. The proxy replaced it with the configured model; see run.json model.',
  'model': 'The model the proxy actually called, from .env MODEL. The name the harness asked for is under model requested.',
  'api': 'Which API shape the harness spoke to the proxy: openai (chat completions) or anthropic (messages). From the recipe.',
  'workdir': 'Directory the agent ran in inside the sandbox. Harbor: the task image\'s WORKDIR. Prompt: the recipe\'s workdir, usually /work.',
  'harness': 'owner-repo slug of the GitHub repo that was packaged; the recipe and overlay image are cached under this name.',
  'taskset': 'The Harbor taskset directory the task came from.',
  'task': 'Harbor: the task folder name. Prompt: the text given on the command line (shown in full below).',
  'started': 'When run.sh wrote the origin half of run.json, just before the proxy started.',
  'finished': 'When the result half was merged into run.json, after the verifier (if any). "not yet" means the run is still going or the runner died.',
  'first call': 'Timestamp of the first model call the proxy recorded.',
  'run': 'Folder name under runs/: timestamp or --run-id, plus -<task> and -k<i> for a Harbor task.',
}
