# recipe.sh — stages 3 and 4: ask the AI for a sandbox recipe, build the overlay from it, and feed a failure
# back for another try.  The recipe file itself is handled by lib/recipe.py; the standing prompt is
# lib/analyze-prompt.md and the schema the analyzer must match is lib/recipe-schema.json.  Sourced by run.sh.

recipe_field() { python3 "$HERE/lib/recipe.py" field "$RECIPE" "$@"; }
# recipe_ok: the saved recipe has every field this version needs and its Dockerfile is an overlay (older recipes are re-analyzed)
recipe_ok() { python3 "$HERE/lib/recipe.py" ok "$RECIPE" 2>/dev/null; }
recipe_hash() { python3 "$HERE/lib/recipe.py" hash "$RECIPE"; }

# analyze <feedback>: claude -p reads the clone and returns the recipe.  $1 is the error from a failed build or
# check, empty on the first try.  The standing prompt never changes; what does is the repository tree and the
# three blocks below — the benchmark task image the overlay must also build on, the recipe that worked for an
# earlier commit of this repo, and the failure to fix.
analyze() {
  local tree; tree="$(cd "$SRC" && find . -maxdepth 2 -not -path './.git*' -not -path './node_modules*' | sort | head -150)"
  local prompt body; body="$(cat "$HERE/lib/analyze-prompt.md")"
  prompt="${body//\{\{REPO_URL\}\}/https://github.com/$OWNER/$REPO}
$tree"
  [ -n "$FIRST_TASK_DF" ] && prompt="$prompt

The overlay will also be built FROM this benchmark task image (its Dockerfile, comments stripped); the check command must pass there too:
$FIRST_TASK_DF"
  [ -z "$1" ] && [ -n "$SEED" ] && prompt="$prompt

A RECIPE FOR AN EARLIER COMMIT OF THIS REPO ($SEED_COMMIT) BUILT, PASSED ITS CHECK AND RAN. This clone is at $COMMIT.
Start from it and return it UNCHANGED unless this commit changed something it depends on (the entrypoint or CLI flags,
manifests or lockfiles, build steps, runtime versions, env variables, config file formats). Change only what that
requires. Results are compared across commits, so an unneeded change to the Docker setup is a cost, not an improvement.
$(cat "$SEED")"
  [ -n "$1" ] && prompt="$prompt

THE PREVIOUS RECIPE FAILED. Fix it. Previous recipe:
$(cat "$RECIPE" 2>/dev/null)

Error output:
$1"
  local raw
  raw="$(cd "$SRC" && claude -p "$prompt" --output-format json --json-schema "$(cat "$HERE/lib/recipe-schema.json")" \
          --allowedTools "Read,Glob,Grep" --max-turns 60 --strict-mcp-config ${ANALYZER_MODEL:+--model "$ANALYZER_MODEL"} 2>"$WORK/analyze.stderr" || true)"
  printf '%s' "$raw" > "$WORK/analyze.raw.json"
  python3 "$HERE/lib/recipe.py" save "$WORK/analyze.raw.json" "$RECIPE" "$WORK/Dockerfile" || return 1
}
# write_wrapper: the script every run execs inside the sandbox — run-harness <workdir> <instruction-file>
write_wrapper() {
  { printf '#!/bin/bash\n# generated by run.sh from recipe.json: run-harness <workdir> <instruction-file>\n'
    printf '[ -n "${HR_PATH:-}" ] && export PATH="$HR_PATH"\nmkdir -p "$1" /out /logs/agent 2>/dev/null; cd "$1"\nTASK="$(cat "$2")"; export TASK\n'
    recipe_field run_command; } > "$WRAPPER"; chmod +x "$WRAPPER"
}
check_image() {  # $1 = image: run the recipe's check command inside it, no network
  local chk; chk="$(recipe_field check_command)"
  docker run --rm --platform "$PLATFORM" --network none -e "HR_PATH=$(image_path "$1")" "$1" bash -lc "$PRELUDE$chk" > "$WORK/check.log" 2>&1 \
    || { echo "check command failed in $1: $chk"; tail -40 "$WORK/check.log"; return 1; }
}
recipe_hash() { python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest()[:16])' "$RECIPE"; }
BUILT=" "
build_overlay() {  # $1 = base image, $2 = tag, $3 = force(0/1): docker build the overlay FROM $1, then the check
  case "$BUILT" in *" $2 "*) return 0;; esac
  # an existing image is reused only if it was built from this commit, this recipe and for this platform
  local rh; rh="$(recipe_hash)"
  if [ "$3" = 0 ] && [ "$(image_platform "$2")" = "$PLATFORM" ] && [ "$(image_label "$2" hr.commit)" = "$COMMIT" ] \
     && [ "$(image_label "$2" hr.recipe)" = "$rh" ]; then echo "overlay $2 exists (${COMMIT:0:7}, recipe $rh, $PLATFORM)"; BUILT="$BUILT$2 "; return 0; fi
  docker build -q --platform "$PLATFORM" --label hr.commit="$COMMIT" --label hr.recipe="$rh" \
    --build-arg BASE="$1" -t "$2" -f "$WORK/Dockerfile" "$SRC" > "$WORK/build.log" 2>&1 \
    || { echo "docker build FROM $1 failed:"; tail -40 "$WORK/build.log"; return 1; }
  echo "overlay $2 built FROM $1"
  check_image "$2" || return 1
  echo "check passed in $2"; BUILT="$BUILT$2 "
}
overlay_tag() { echo "$IMAGE/$TS_NAME:$1"; }

# prepare_recipe: a recipe that builds and passes its check, in at most three tries, then kept for this commit.
# Recipes are kept per commit: recipes/<name>@<sha>.json. The same commit reuses its recipe (no AI call); a new commit is
# analyzed, seeded with the newest working recipe for this repo; --rebuild analyzes from scratch.
# PREV is what the final recipe is diffed against (recipe.diff), so a changed result can be traced to a changed Docker setup.
prepare_recipe() {
  STORE="$HERE/recipes"; STORED="$STORE/$NAME@$COMMIT.json"; mkdir -p "$STORE"
  SEED=""; SEED_COMMIT=""; PREV=""; NEED_ANALYZE=0; FORCE=0
  if [ "$REBUILD" = 0 ] && [ -f "$STORED" ]; then
    cp "$STORED" "$RECIPE"; cp "$STORED" "$WORK/prev.recipe.json"; PREV="$WORK/prev.recipe.json"
    recipe_ok || { echo "recipes/$NAME@${COMMIT:0:12}.json is from an older schema (not an overlay); re-analyzing"; NEED_ANALYZE=1; }
  else
    NEED_ANALYZE=1
    if [ "$REBUILD" = 0 ]; then
      SEED="$(ls -t "$STORE/$NAME@"*.json 2>/dev/null | head -1 || true)"
      if [ -n "$SEED" ]; then SEED_COMMIT="$(basename "$SEED" .json)"; SEED_COMMIT="${SEED_COMMIT##*@}"
      elif [ -f "$RECIPE" ] && recipe_ok; then  # a recipe from before the per-commit store; its commit is not known
        cp "$RECIPE" "$WORK/seed.recipe.json"; SEED="$WORK/seed.recipe.json"; SEED_COMMIT="unknown (work/$NAME/recipe.json)"; fi
      [ -z "$SEED" ] || { cp "$SEED" "$WORK/prev.recipe.json"; PREV="$WORK/prev.recipe.json"; }
    fi
  fi
  FEEDBACK=""; OK=0
  for attempt in 1 2 3; do
    if [ "$NEED_ANALYZE" = 1 ]; then
      stage analyze "attempt $attempt: claude -p reads the repo at ${COMMIT:0:7} and writes the recipe$([ -n "$SEED" ] && [ -z "$FEEDBACK" ] && echo ", seeded with the recipe for ${SEED_COMMIT:0:12}")"
      if A="$(analyze "$FEEDBACK" 2>&1)"; then echo "$A"; else echo "$A"; FEEDBACK="$A"; emit type recipe mode failed attempt "$attempt"; continue; fi
      FORCE=1; emit type recipe mode analyzed attempt "$attempt" seeded_from "${SEED_COMMIT:-none}"
    else
      stage analyze "recipe exists for ${COMMIT:0:7}: recipes/$NAME@${COMMIT:0:12}….json (no AI call; --rebuild to regenerate)"
      recipe_field dockerfile > "$WORK/Dockerfile"; emit type recipe mode reused
      echo "api=$(recipe_field api_style)  base=$(recipe_field base_image)  run_command: $(recipe_field run_command)"
    fi
    write_wrapper
    stage build "overlay FROM $(recipe_field base_image)${FIRST_TASK_IMG:+ and FROM $FIRST_TASK_IMG}"
    if ERR="$( { build_overlay "$(recipe_field base_image)" "$IMAGE" "$FORCE" && { [ -z "$FIRST_TASK_IMG" ] || build_overlay "$FIRST_TASK_IMG" "$(overlay_tag "${TASKS[0]}")" "$FORCE"; }; } 2>&1 )"; then
      echo "$ERR"; OK=1; break
    else echo "$ERR"; FEEDBACK="$ERR"; NEED_ANALYZE=1; fi
  done
  [ "$OK" = 1 ] || die "could not build a working sandbox after 3 attempts; see work/$NAME/{build.log,check.log,analyze.stderr}"
  # the recipe built and passed its check: keep it for this commit, and say how it differs from the one before it
  [ "$FORCE" = 1 ] && { cp "$RECIPE" "$STORED"; echo "recipe saved: recipes/$(basename "$STORED")"; }
  emit type built image "$IMAGE" platform "$PLATFORM"
  rm -f "$WORK/recipe.diff"
  if [ -n "$PREV" ]; then python3 "$HERE/lib/recipe.py" diff "$PREV" "$RECIPE" "$WORK/recipe.diff"; fi
}
